// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3tBnOKiphGXwOMPp3Xmw5RBT86vg297Q',
    appId: '1:360621076334:web:7c85518fc28853b4855b7f',
    messagingSenderId: '360621076334',
    projectId: 'pp-edtech',
    authDomain: 'pp-edtech.firebaseapp.com',
    storageBucket: 'pp-edtech.appspot.com',
    measurementId: 'G-YSFEYDPKBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1cK21rJcyK410P71zAWTf4f6W_fhgGOk',
    appId: '1:360621076334:android:c49ad5e1909867ec855b7f',
    messagingSenderId: '360621076334',
    projectId: 'pp-edtech',
    storageBucket: 'pp-edtech.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqE143RpdPKS-FMXXHd8fv6Pq9BtCZWjs',
    appId: '1:360621076334:ios:2060d692f68b08b0855b7f',
    messagingSenderId: '360621076334',
    projectId: 'pp-edtech',
    storageBucket: 'pp-edtech.appspot.com',
    iosClientId: '360621076334-iimd3gkvhiq647pgodt6bnm448te01tk.apps.googleusercontent.com',
    iosBundleId: 'com.example.ppEdtech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqE143RpdPKS-FMXXHd8fv6Pq9BtCZWjs',
    appId: '1:360621076334:ios:2060d692f68b08b0855b7f',
    messagingSenderId: '360621076334',
    projectId: 'pp-edtech',
    storageBucket: 'pp-edtech.appspot.com',
    iosClientId: '360621076334-iimd3gkvhiq647pgodt6bnm448te01tk.apps.googleusercontent.com',
    iosBundleId: 'com.example.ppEdtech',
  );
}
